services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: buplana-db
      POSTGRES_PASSWORD: mypw
      POSTGRES_USER: buplana-db-admin
    ports:
      - 5432:5432
    volumes:
      # init db
      - ./deployment/db:/docker-entrypoint-initdb.d/