-- user is a reserved keyword
CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL,
                       create_date TIMESTAMP NOT NULL
);

CREATE TABLE budget (
                        budget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(20) NOT NULL,
                        user_id BIGINT NOT NULL,
                        CONSTRAINT fk_budget_user FOREIGN KEY (user_id)
                            REFERENCES users (user_id) ON DELETE CASCADE,
                        CONSTRAINT uk_budget_user_name UNIQUE (user_id, name)
);

CREATE TABLE tag (
                     tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(20) NOT NULL,
                     tag_type VARCHAR(20) NOT NULL,
                     user_id BIGINT NULL,
                     CONSTRAINT fk_tag_user FOREIGN KEY (user_id)
                         REFERENCES users (user_id) ON DELETE CASCADE,
                     CONSTRAINT uk_tag_user_name UNIQUE (user_id, name)
);

CREATE TABLE expense (
                         expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         amount DECIMAL(12,2) NOT NULL CHECK (amount > 0),
                         note VARCHAR(255),
                         frequency VARCHAR(20) NOT NULL,
                         budget_id BIGINT NOT NULL,
                         tag_id BIGINT NOT NULL,
                         date DATE NOT NULL,
                         CONSTRAINT fk_expense_budget FOREIGN KEY (budget_id)
                             REFERENCES budget (budget_id) ON DELETE CASCADE,
                         CONSTRAINT fk_expense_tag FOREIGN KEY (tag_id)
                             REFERENCES tag (tag_id) ON DELETE CASCADE
);